
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: image-cloud

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  config:
    import: optional:credentials.yaml

